### PR TITLE
Move data into a json file

### LINKED ISSUE #12: Figure out how to parse JSON into the `prepublish` process
The file [usa-map-dimensions.js](https://github.com/gabidavila/react-usa-map/blob/master/src/data/usa-map-dimensions.js) in the beginning of developing this package was supposed to be a `usa-map-dimensions.json`. Right now I am doing a workaround declaring the data as a javascript constant, however I think architecturally speaking this is better since JSON purpose is to store data.

### PR DESCRIPTION
**Pull request by emman27**
Moved data out. Should fit your requirements. Note the relative path.

It's also possible to abstract the path into an absolute path, and replace this with an environment variable declared at compile-time

Fixes #12 (Whoops got this number wrong)

### CODE REVIEW

**Comment by gabidavila** [comment]
Problem is `prepublish` doesn't move the `.json` file to the `dist` folder. That is the main issue actually...

**Comment by emman27** [comment]
Ah sorry that was quite silly of me. I've made the necessary fixes.

**Comment by gabidavila** [comment]
Some package missing on `package.json`? 

```
ReferenceError: Unknown plugin "inline-json-import" specified in "/home/travis/build/gabidavila/react-usa-map/.babelrc" at 0, attempted to resolve relative to "/home/travis/build/gabidavila/react-usa-map"
```

**Comment by emman27** [comment]
My bad. Missed making a commit ><

**Comment by gabidavila** [comment]
Closes #12

**Comment by gabidavila** [comment]
@emman27, can you PR this again? I had to change the `dev` branch and lost the merge. I want to keep the track of your contribution and not just copy and paste it. Thanks.

**Pull request merged**
