### PR TITLE
Add cursotm clickHandler to state configuration

### PR DESCRIPTION
**Pull request by AlithAnar**
I don't fully understand the issue #1, but this change adds ability to define custom clickHandler callback for specified state.

### CODE REVIEW

**Comment by gabidavila** [comment]
That is really close to what I meant, I am gonna try to add some tests for before merging it to master. @willmendesneto Thanks for the tests you did earlier, do you think you could help with this? That is ok if you don't have the time.

**Comment by willmendesneto** [comment]
@AlithAnar to add some tests for that case you need to

- Add a new `clickHandler` object with a method at the [`customize` test object](https://github.com/gabidavila/react-usa-map/blob/master/src/__tests__/usa-map-dimensions.js#L21..L24);
-Change the current scenario to check when it doesn't have a customised `clickHandler`. 
It will be change the description of [this test](https://github.com/gabidavila/react-usa-map/blob/master/src/__tests__/usa-map-dimensions.js#L46..L51);
- After that, create a new test using your new object with a method customized.

EX:

```js
const customisedClickHandleMock = jest.fn();
...
componentProps = {
      width: 959,
      height: 593,
      defaultFill: "#D3D3D3",
      title: "Blank US states map",
      customize: {
        "AK": {
          fill: "dummy-fill"
        }
        "HI": {
          fill: "another-dummy-fill",
          clickHandler: customisedClickHandleMock
        }
      },
      onClick: onClickMock
    };
    element = shallow(<USAMap {...componentProps} />);
...
 it("should calls customise method is customise property has click handler", () => {
    const statesLength = element.find(`USAState[fill="${componentProps.customize.HI.fill}"]`);
    state.simulate("click");
   expect(customisedClickHandleMock.mock.calls[0]).toEqual([undefined]); // or the received data
  });
```

**Comment by AlithAnar** [comment]
Ok, I'll handle this after my work

**Comment by AlithAnar** [comment]
Test for this case is added. I wrote also a comment about simulating click on Parent - Children case.

**Comment by gabidavila** [comment]
Gonna look at it soon 👍

**Pull request merged**
