### PR TITLE
Updated to allow strings for width and height

### PR DESCRIPTION
**Pull request by jacob-ebey**

### CODE REVIEW

**Comment by jacob-ebey** [comment]
Allowing a string for width and height will allow for things like width="100%" height="auto". This is necessary for responsive websites.

**Comment by ljmerza** [comment]
@gabidavila what's the status on this? The map isn't responsive without being able to use strings/booleans

**Comment by jacob-ebey** [comment]
Feel free to merge at any point

**Comment by jacob-ebey** [comment]
Merge this within the month or I'm closing the PR to free up dashboard space.

**Comment by jacob-ebey** [comment]
It's been like 9 months without a response, I'm considering this project dead.

**Pull request closed without merging**
