### PR TITLE
State name dispaly on hover of any state.

### PR DESCRIPTION
**Pull request by sachinlamba**
I was using this package in one of my project. What I found was that there is no hover title for state. So I implemented that if u hover on any state,it will give the name of that state. Plz check if its ok to merge it.

### CODE REVIEW

**Comment by gabidavila** [comment]
Sorry for the delay on this, I will test this week and merge and release the new package version

**Comment by kwent** [comment]
Hi @gabidavila. Thanks for this amazing library. Is there any ETA to release this feature ?

Regards

**Comment by ymihir** [comment]
Hello @gabidavila , any update on this? you have created a very nice feature but i am requesting you to add few more details to it which will look awesome.

**Comment by gabidavila** [comment]
Working on it now!

**Pull request merged**
